version: "3"
services:
    web:
        build: ./app
        command: python app.py
        volumes:
            - ./shared:/code/shared
        ports:
            - 5000:5000
        depends_on:
            - redis
            - gentle
        env_file:
            - app.env
    gentle:
        image: lowerquality/gentle
    worker:
        build: ./worker
        command: rq worker -u redis://redis:6379
        volumes:
            - ./shared:/code/shared
        depends_on:
            - redis
            - gentle
            - web
        env_file:
            - .env
    redis:
        image: redis:latest
